# Generated by Django 5.1 on 2024-09-23 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(editable=False, max_length=100, unique=True),
        ),
    ]
