# Generated by Django 5.1 on 2024-10-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bank_account_number_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number_format',
            field=models.CharField(default='xxxxxxxxxxxxxxxxxx', max_length=16, unique=True),
        ),
    ]
