# Generated by Django 5.1 on 2024-10-15 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boss',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Boss', 'Boss')], default='Employee', max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Boss', 'Boss')], default='Employee', max_length=10),
        ),
        migrations.AddField(
            model_name='manager',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Boss', 'Boss')], default='Employee', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendingemployee',
            name='department_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
