# Generated by Django 5.1 on 2024-10-30 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0002_boss_role_employee_department_id_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployee',
            name='password',
            field=models.CharField(default='12345678', max_length=128),
        ),
    ]
