# Generated by Django 5.1 on 2024-11-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0002_alter_person_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Manager', 'Manager'), ('Boss', 'Boss'), ('Customer', 'Customer')], default='', max_length=10),
        ),
    ]
