# Generated by Django 5.1 on 2024-10-30 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0003_pendingemployee_password'),
        ('bank', '0005_alter_bank_account_number_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingemployee',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
