# Generated by Django 5.1 on 2024-10-30 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0004_pendingemployee_bank'),
        ('bank', '0005_alter_bank_account_number_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingemployee',
            name='bank',
            field=models.ForeignKey(default='meli', on_delete=django.db.models.deletion.CASCADE, to='bank.bank'),
        ),
    ]
