# Generated by Django 5.1 on 2024-10-30 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bankusers', '0005_alter_pendingemployee_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='pendingemployee',
            name='hire_date',
        ),
    ]
