# Generated by Django 5.1 on 2024-09-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='address',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.bank'),
        ),
    ]
