# Generated by Django 5.1 on 2024-09-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_bankaccount_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='bank_name',
        ),
    ]
