# Generated by Django 5.1 on 2024-10-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_bankaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='transaction_password',
            field=models.CharField(default='0000', max_length=4),
        ),
    ]
