# Generated by Django 5.1 on 2024-10-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
